version: "3.7"

services:
  poc-db:
    image: postgres:13.1
    ports:
      - "5432:5432"
    volumes:
      - ./packages/api/init-db.sh:/docker-entrypoint-initdb.d/01-init-api-db.sh
    env_file:
      - ./packages/api/.env


